[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-app"
version = "0.0.23"
description = "Helpers for building Python app or cli."
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pip-tools",
    "pydantic",
    "pytest",
    "python-dotenv",
    "wexample-filestate==0.0.26",
    "wexample-helpers-yaml==0.0.25",
    "wexample-helpers==0.0.26",
    "wexample-prompt==0.0.25",
    "wexample-wex-addon-app==0.0.20",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-app"

[tool.setuptools.packages.find]
include = [
    "*",
]
