[build-system]
requires = ["pdm-backend>=2.2"]
build-backend = "pdm.backend"

[project]
name = "app-manager"
version = "0.0.1"
description = "App manager entrypoint"
requires-python = ">=3.10"
dependencies = [
    "wexample-wex-core>=0.1.0",
]

[tool.pdm]
distribution = true
