[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "files-state"
version = "0.1.0"
description = "Files state app"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
files-state = "files_state.app:main"
